GET http://localhost:3333/health

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/080a9bf3-13d2-48b4-9d0a-355ea851d95c

###

POST http://localhost:3333/courses
Content-Type: application/json

{
  "title":"Curso de React",
  "description":"Curso de react 19"
}

###

DELETE  http://localhost:3333/courses/3

###

PATCH http://localhost:3333/courses/2
Content-Type: application/json

{
  "title":"Curso de React e Next.js"
}