GET http://localhost:3333/health

###

GET http://localhost:3333/courses?limit=10&search=victor

###

GET http://localhost:3333/courses/6bfcf93e-eba0-4fde-8c0c-c355457bb8bc
###

POST http://localhost:3333/courses
Content-Type: application/json

{
  "title":"Curso de Angular"
}

###

DELETE  http://localhost:3333/courses/cada1b29-de02-4f92-afc1-e2511c1f2a97

###

PATCH http://localhost:3333/courses/6bfcf93e-eba0-4fde-8c0c-c355457bb8bc
Content-Type: application/json

{
  "description":"Curso de spring boot ensinado pelo professor João Victor"
}